import { Metadata } from "next"
import Content from "./content"
export const metadata: Metadata = {
  title: "Open Source Immersion - Risk Horizon ASBL",
  description:
    "Le salon Open Source Immersion (OSI) est un événement organisé par Risk Horizon ASBL pour promouvoir les logiciels libres et open source.",
  authors: [
    { name: "Risk Horizon" },
    { name: "Maxime Curon" },
    { name: "Guillaume Richard" },
    { name: "Guillaume Rosin" },
  ],
  keywords: [
    "risque",
    "horizon",
    "risque horizon",
    "NRJ",
    "HEH",
    "19 octobre",
    "Mons",
    "Open Source Immersion",
    "OSI",
    "Risk Horizon",
    "ASBL",
    "Logiciels libres",
    "Open source",
    "Software",
    "Logiciel",
    "Informatique",
    "Cybersécurité",
    "Cybersecurity",
    "Sécurité informatique",
    "Sécurité des données",
    "Data security",
    "Sécurité des réseaux",
    "Network security",
    "Sécurité des applications",
    "Application security",
    "Sécurité des logiciels",
    "Software security",
    "Sécurité des systèmes d'information",
    "Information system security",
    "Sécurité des systèmes informatiques",
    "Sécurité des systèmes d'exploitation",
    "Operating system security",
    "Sécurité des systèmes embarqués",
    "Embedded system security",
    "Sécurité des systèmes industriels",
    "Industrial system security",
    "Sécurité des systèmes de contrôle",
    "Control system security",
    "Sécurité des systèmes de gestion",
    "Management system security",
    "Sécurité des systèmes de communication",
    "Communication system security",
    "Sécurité des systèmes de transport",
    "Transport system security",
    "Sécurité des systèmes",
    "System security",
    "Maxime Curon",
    "Guillaume Richard",
    "Guillaume Rosin",
    "Guillaume",
    "Richard",
    "Rosin",
    "Curon",
  ],
  creator: "Risk Horizon",
  publisher: "Risk Horizon",
  icons: ["favicon.ico"],
  openGraph: {
    type: "website",
    locale: "fr_BE",
    url: "https://risk-horizon.be",
    images: [
      {
        url: "https://risk-horizon.be/opengraph-image-osi.png",
        width: 800,
        height: 600,
        alt: "OSI logo",
      },
    ],
  },
  metadataBase: new URL("https://risk-horizon.be"),
}

function Page() {
  return <Content />
}

export default Page
